name: Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build project
      run: mvn clean package -DskipTests
        
    - name: Copy XSD files to resources
      run: |
        mkdir -p xsd
        find libs/edifactconverter -name "*.xsd" -type f -exec cp {} xsd/ \;
        
    - name: Organize XSD files into version folders
      run: |
        cd xsd

        # Dynamically create directories and organize XSD files by version
        for file in *.xsd; do
          if [[ -f "$file" ]]; then
            # Extract version and prefix from filename
            # Supports both EDIFACTINTERCHANGE_APERAK_11A.xsd and ORDRSP_INVOIC_96A.xsd patterns
            if [[ $file =~ ^.*_.*_([0-9][0-9][A-Z])\.xsd$ ]]; then
              prefix="${BASH_REMATCH[1]}"
              version="${BASH_REMATCH[2]}"
              
              # Create directory for this version if it doesn't exist
              mkdir -p "${prefix}_${version}"
              # Move file to appropriate version folder
              mv "$file" "${prefix}_${version}/"
              echo "Organized $file -> ${prefix}_${version}/"
            fi
          fi
        done

    - name: Zip XSD files
      run: |
        zip -r xsd-files.zip xsd/

    - name: Upload XSD files
      uses: actions/upload-artifact@v4
      with:
        name: xsd-files
        path: xsd-files.zip
        retention-days: 30

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          **/target/surefire-reports/
          **/target/test-classes/
          
    - name: Upload JAR artifacts
      uses: actions/upload-artifact@v4
      with:
        name: jar-artifacts
        path: |
          cpitoedifact-converter-core/target/*.jar
        retention-days: 30
        
    - name: Upload fat JAR
      uses: actions/upload-artifact@v4
      with:
        name: fat-jar
        path: cpitoedifact-converter-core/target/*-fat.jar
        retention-days: 30
