name: Build and Test

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java-version: [8, 11, 17]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build libs/edifactconverter module first
      run: |
        cd libs/edifactconverter
        mvn clean install -DskipTests
        
    - name: Run tests
      run: mvn clean test
      
    - name: Build project
      run: mvn clean package -DskipTests
      
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results-java-${{ matrix.java-version }}
        path: |
          **/target/surefire-reports/
          **/target/test-classes/
          
    - name: Upload JAR artifacts
      uses: actions/upload-artifact@v3
      with:
        name: jar-artifacts-java-${{ matrix.java-version }}
        path: |
          cpitoedifact-converter-core/target/*.jar
          libs/edifactconverter/openedifact-converter/target/*.jar
          libs/edifactconverter/openedifact-converter-runnable/target/*.jar
        retention-days: 30
        
    - name: Upload fat JAR
      uses: actions/upload-artifact@v3
      with:
        name: fat-jar-java-${{ matrix.java-version }}
        path: cpitoedifact-converter-core/target/*-fat.jar
        retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build libs/edifactconverter module
      run: |
        cd libs/edifactconverter
        mvn clean install -DskipTests
        
    - name: Build and package
      run: mvn clean package -DskipTests
      
    - name: Create release artifacts
      run: |
        mkdir -p release-artifacts
        cp cpitoedifact-converter-core/target/*.jar release-artifacts/
        cp libs/edifactconverter/openedifact-converter/target/*.jar release-artifacts/
        cp libs/edifactconverter/openedifact-converter-runnable/target/*.jar release-artifacts/
        
    - name: Upload release artifacts
      uses: actions/upload-artifact@v3
      with:
        name: release-artifacts
        path: release-artifacts/
        retention-days: 90
