name: Simple Build

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build libs/edifactconverter module first
      run: |
        cd libs/edifactconverter
        mvn clean install -DskipTests
        
    - name: Run tests
      run: mvn clean test
      
    - name: Build project
      run: mvn clean package -DskipTests
      
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          **/target/surefire-reports/
          **/target/test-classes/
          
    - name: Upload core JAR
      uses: actions/upload-artifact@v4
      with:
        name: cpitoedifact-converter-core
        path: cpitoedifact-converter-core/target/*.jar
        retention-days: 30
        
    - name: Upload fat JAR
      uses: actions/upload-artifact@v4
      with:
        name: cpitoedifact-converter-fat
        path: cpitoedifact-converter-core/target/*-fat.jar
        retention-days: 30
        
    - name: Upload edifactconverter JARs
      uses: actions/upload-artifact@v4
      with:
        name: edifactconverter-libs
        path: |
          libs/edifactconverter/openedifact-converter/target/*.jar
          libs/edifactconverter/openedifact-converter-runnable/target/*.jar
        retention-days: 30
